# Generated by Django 6.0.4 on 2026-04-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id']},
        ),
    ]
